# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5211df7771ecb568b886e82b0c9d2595eedff7e9ef106c8c0041947ebe673064313e3d4e14f45d4526c1b1fd09c9f5862c158ed1bcefe93a6ba8d784b2abf340

test:
  secret_key_base: df637e5f6d8fa993ae11a58a7211df0d0d8c81262205d8d5c5a9ce5ccbe7d7f088b3e785e8c3b9e673e25ebed0fed3df4efe65538c66ab99d11ab9e2d558744d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
